services:
  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emergency_room
    ports:
      - "35434:5432"
    volumes:
      - emergency_room_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6381:6379"

volumes:
  emergency_room_pg:

